image:
  repository: 804054839611.dkr.ecr.eu-central-1.amazonaws.com/django
  tag: v1.0.5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

config:
  POSTGRES_PORT: 5432
  POSTGRES_HOST: db
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: pass9764gd